require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/prerequisites", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Prerequisite. As you add validations to Prerequisite, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Prerequisite.create! valid_attributes
      get prerequisites_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      prerequisite = Prerequisite.create! valid_attributes
      get prerequisite_url(prerequisite)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_prerequisite_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      prerequisite = Prerequisite.create! valid_attributes
      get edit_prerequisite_url(prerequisite)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Prerequisite" do
        expect {
          post prerequisites_url, params: { prerequisite: valid_attributes }
        }.to change(Prerequisite, :count).by(1)
      end

      it "redirects to the created prerequisite" do
        post prerequisites_url, params: { prerequisite: valid_attributes }
        expect(response).to redirect_to(prerequisite_url(Prerequisite.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Prerequisite" do
        expect {
          post prerequisites_url, params: { prerequisite: invalid_attributes }
        }.to change(Prerequisite, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post prerequisites_url, params: { prerequisite: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested prerequisite" do
        prerequisite = Prerequisite.create! valid_attributes
        patch prerequisite_url(prerequisite), params: { prerequisite: new_attributes }
        prerequisite.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the prerequisite" do
        prerequisite = Prerequisite.create! valid_attributes
        patch prerequisite_url(prerequisite), params: { prerequisite: new_attributes }
        prerequisite.reload
        expect(response).to redirect_to(prerequisite_url(prerequisite))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        prerequisite = Prerequisite.create! valid_attributes
        patch prerequisite_url(prerequisite), params: { prerequisite: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested prerequisite" do
      prerequisite = Prerequisite.create! valid_attributes
      expect {
        delete prerequisite_url(prerequisite)
      }.to change(Prerequisite, :count).by(-1)
    end

    it "redirects to the prerequisites list" do
      prerequisite = Prerequisite.create! valid_attributes
      delete prerequisite_url(prerequisite)
      expect(response).to redirect_to(prerequisites_url)
    end
  end
end
